# Lab | Numpy Deep Dive

**1\. Import the NUMPY package under the name np.**

In [288]:
import numpy as np;

**2\. Print the NUMPY version and the configuration.**

In [289]:
print(np.version.version);

1.15.4


**3\. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a".**

**Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?**



In [290]:
a = np.random.randint(10, size = (2,3,5));
a = np.random.rand(2,3,5);
a = np.random.random((2,3,5));

There are many ways to generate random samples. More can be found here: [Random sampling with NumPy](https://docs.scipy.org/doc/numpy-1.14.1/reference/routines.random.html)


**4\. Print a.**

In [291]:
print(a);

[[[0.39710984 0.15710628 0.08751183 0.23144221 0.76265726]
  [0.60080638 0.96939632 0.88241606 0.73277615 0.42741788]
  [0.4689832  0.88249894 0.77202558 0.52478669 0.99062469]]

 [[0.01821587 0.80211227 0.58996401 0.42462446 0.41255853]
  [0.64650034 0.82988423 0.88052258 0.26082866 0.36086414]
  [0.52805015 0.96642267 0.57791751 0.24901811 0.83058673]]]


**5\. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable "b".**

In [292]:
b = np.ones((5,2,3));

**6\. Print b.**

In [293]:
print(b);

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


**7\. Do a and b have the same size? How do you prove that in Python code?**

Yes, they have the same size.

In [294]:
print(a.size == b.size);

True


**8\. Are you able to add a and b? Why or why not?**

No, because even though they have the same size, they don't have the same shape. The shape of a is (3,2,3,5) while the shape of b is (3,5,2,3).

In [295]:
print(a.shape == b.shape);

False


If we try to add a and b, we get an error.

In [296]:
np.add(a, b);

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

**9\. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".**

In [297]:
print(a.shape, '-', b.shape);

(2, 3, 5) - (5, 2, 3)


In [298]:
c = np.transpose(b, [1, 2, 0]);

In [299]:
print(a.shape, '-', c.shape);

(2, 3, 5) - (2, 3, 5)


**10\. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?**

It works because now the two arrays have the same shape, therefore they can be added.

In [300]:
d = np.add(a,c);

**11\. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.**

The relation between terms in a and d is: 

d[n][m][p] = a[n][m][p] + c[n][m][p] 

when c[n][m][p] = 1, n = {0,1}, m = {0,1,2}, p = {0,1,2,3,4}.

We add one to every element in a. 

In [301]:
print('A');
print(a);
print('D');
print(d);

A
[[[0.39710984 0.15710628 0.08751183 0.23144221 0.76265726]
  [0.60080638 0.96939632 0.88241606 0.73277615 0.42741788]
  [0.4689832  0.88249894 0.77202558 0.52478669 0.99062469]]

 [[0.01821587 0.80211227 0.58996401 0.42462446 0.41255853]
  [0.64650034 0.82988423 0.88052258 0.26082866 0.36086414]
  [0.52805015 0.96642267 0.57791751 0.24901811 0.83058673]]]
D
[[[1.39710984 1.15710628 1.08751183 1.23144221 1.76265726]
  [1.60080638 1.96939632 1.88241606 1.73277615 1.42741788]
  [1.4689832  1.88249894 1.77202558 1.52478669 1.99062469]]

 [[1.01821587 1.80211227 1.58996401 1.42462446 1.41255853]
  [1.64650034 1.82988423 1.88052258 1.26082866 1.36086414]
  [1.52805015 1.96642267 1.57791751 1.24901811 1.83058673]]]


**12\. Multiply a and c. Assign the result to e.**


In [302]:
e = np.multiply(a,c);

**13\. Does e equal to a? Why or why not?**

Yes. The relation between terms in a and e is: 

e[n][m][p] = a[n][m][p] * c[n][m][p]

when c[n][m][p] = 1, n = {0,1}, m = {0,1,2}, p = {0,1,2,3,4}.

We multiply by 1 every element in a, so the resulting array e should be equal to a.

In [303]:
print(a == e);

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


**14\. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"**

In [304]:
d_max = np.max(d);
d_min = np.min(d);
d_mean = np.mean(d);

In [305]:
print('MAX:  ', d_max);
print('MIN:  ', d_min);
print('MEAN: ', d_mean);

MAX:   1.99062469068988
MIN:   1.0182158684842428
MEAN:  1.575520985533566


**15\. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.**

In [306]:
f = np.empty((2, 3, 5), dtype=np.int8);

**16\. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.**

In [307]:
it = np.nditer(d, flags=['multi_index']);
while not it.finished:
    if it[0] == d_min:
        f[it.multi_index] = 0;
    elif it[0] > d_min and it[0] < d_mean:
        f[it.multi_index] = 25;
    elif it[0] == d_mean:
        f[it.multi_index] = 50;
    elif it[0] > d_mean and it[0] < d_max:
        f[it.multi_index] = 75;
    else:
        f[it.multi_index] = 100;
    it.iternext()

**17\. Print d and f. Do you have your expected f?**

Yes!

In [308]:
print('D');
print(d);
print('F');
print(f);

D
[[[1.39710984 1.15710628 1.08751183 1.23144221 1.76265726]
  [1.60080638 1.96939632 1.88241606 1.73277615 1.42741788]
  [1.4689832  1.88249894 1.77202558 1.52478669 1.99062469]]

 [[1.01821587 1.80211227 1.58996401 1.42462446 1.41255853]
  [1.64650034 1.82988423 1.88052258 1.26082866 1.36086414]
  [1.52805015 1.96642267 1.57791751 1.24901811 1.83058673]]]
F
[[[ 25  25  25  25  75]
  [ 75  75  75  75  25]
  [ 25  75  75  25 100]]

 [[  0  75  75  25  25]
  [ 75  75  75  25  25]
  [ 25  75  75  25  75]]]


**18\. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements?**

In [309]:
g = np.empty((2, 3, 5), dtype=str);
it = np.nditer(d, flags=['multi_index']);
while not it.finished:
    if it[0] == d_min:
        g[it.multi_index] = 'A';
    elif it[0] > d_min and it[0] < d_mean:
        g[it.multi_index] = 'B';
    elif it[0] == d_mean:
        g[it.multi_index] = 'C';
    elif it[0] > d_mean and it[0] < d_max:
        g[it.multi_index] = 'D';
    else:
        g[it.multi_index] = 'E';
    it.iternext()

In [311]:
print('G');
print(g);

G
[[['B' 'B' 'B' 'B' 'D']
  ['D' 'D' 'D' 'D' 'B']
  ['B' 'D' 'D' 'B' 'E']]

 [['A' 'D' 'D' 'B' 'B']
  ['D' 'D' 'D' 'B' 'B']
  ['B' 'D' 'D' 'B' 'D']]]
